module BlobTileGeneratorSpec
    ( spec
    ) where

import           BlobTileGenerator       (generateBlobTile)
import           Codec.Picture           (PixelRGBA8 (PixelRGBA8), convertRGBA8,
                                          generateImage, readImage)
import           Data.Either.Combinators (fromRight')
import           Data.Maybe              (isNothing)
import           Test.Hspec              (Spec, describe, it, runIO)

spec :: Spec
spec = testGenerateBlobTile

testGenerateBlobTile :: Spec
testGenerateBlobTile = do
    input <- readImage' "tests/input.png"
    expected <- readImage' "tests/expected.png"
    describe "generateBlobTile" $ do
        it
            "returns a Just value containing a blob tile generated by the passed 1x5 tile image" $
            generateBlobTile input == Just expected
        it "returns a Nothing if the given tile file has an incorrect size." $
            isNothing (generateBlobTile invalidSizeImage)
  where
    readImage' = runIO . fmap (convertRGBA8 . fromRight') . readImage
    invalidSizeImage = generateImage (\_ _ -> PixelRGBA8 0 0 0 0) 1 1
